# -*- coding: utf-8 -*-
"""Global_AI_Content_Impact

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQsUpWoOQht7tIiQt_8-HFBISSD9V0SX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Data

from google.colab import files
upload = files. upload()

df = pd.read_csv("/content/Global_AI_Content_Impact_Dataset.csv")

# Data Analysis

df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.dtypes

print("Dataset Shape:", df.shape)

print(df.columns)

# Correlation Heatmap

from numpy._core import numeric
import matplotlib.pyplot as plt
import seaborn as sns

numeric_columns = df.select_dtypes(include=[np.number]).columns
plt.figure(figsize=(10,6))
sns.heatmap(df[numeric_columns].corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")

# Industry Distribution

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(12,6))
sns.countplot(x='Industry', data=df)
plt.title("Industry Distribution")
plt.show()

# Industry Distribution by Country

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,6))
sns.countplot(x='Industry', hue='Country', data=df)
plt.title("Industry Distribution by Country")
plt.show()

# Convert object columns to category for cleaner analysis

cat_cols = ['Country', 'Industry', 'Top AI Tools Used', 'Regulation Status']
for col in cat_cols:
    df[col] = df[col].astype('category')

# AI Adoption Rate Over Years

plt.figure(figsize=(12,6))
sns.lineplot(data=df, x="Year", y="AI Adoption Rate (%)", hue="Industry")
plt.title("AI Adoption Trend Over Years by Industry")
plt.show()

# Job Loss Trend

plt.figure(figsize=(12,6))
sns.lineplot(data=df, x="Year", y="Job Loss Due to AI (%)", hue="Country")
plt.title("Job Loss Trend Over Years by Country")
plt.show()

# Job Loss by Industry

plt.figure(figsize=(12,6))
sns.barplot(data=df, x="Industry", y="Job Loss Due to AI (%)", estimator='mean')
plt.title("Average Job Loss Due to AI by Industry")
plt.xticks(rotation=45)
plt.show()

# Revenue Increase by Industry

plt.figure(figsize=(12,6))
sns.barplot(data=df, x="Industry", y="Revenue Increase Due to AI (%)")
plt.title("Revenue Increase by Industry")
plt.xticks(rotation=45)
plt.show()

#  AI Risk Score

df["AI_Risk_Score"] = (
    0.5 * df["Job Loss Due to AI (%)"] +
    0.3 * df["AI Adoption Rate (%)"] +
    0.2 * df["AI-Generated Content Volume (TBs per year)"]
)

# Plot AI Risk Score by Industry

plt.figure(figsize=(12,6))
sns.barplot(data=df, x="Industry", y="AI_Risk_Score")
plt.title("Industry-wise AI Risk Score")
plt.xticks(rotation=45)
plt.show()

# Consumer Trust vs Job Loss

plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x="Consumer Trust in AI (%)", y="Job Loss Due to AI (%)", hue="Industry")
plt.title("Consumer Trust vs Job Loss")
plt.show()

# Revenue vs Job Loss

plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x="Revenue Increase Due to AI (%)", y="Job Loss Due to AI (%)", hue="Industry")
plt.title("Revenue vs Job Loss")
plt.show()

# AI Adoption vs Regulation Status

plt.figure(figsize=(10,6))
sns.boxplot(data=df, x="Regulation Status", y="AI Adoption Rate (%)")
plt.title("AI Adoption vs Regulation Status")
plt.show()

# Most Used AI Tools

plt.figure(figsize=(10,5))
sns.countplot(data=df, x="Top AI Tools Used")
plt.title("Most Used AI Tools")
plt.xticks(rotation=45)
plt.show()

# ML Modle

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df[[
    "AI Adoption Rate (%)",
    "AI-Generated Content Volume (TBs per year)",
    "Revenue Increase Due to AI (%)",
    "Human-AI Collaboration Rate (%)",
    "Consumer Trust in AI (%)",
    "Market Share of AI Companies (%)"
]]

y = df["Job Loss Due to AI (%)"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

print("Model Score:", model.score(X_test, y_test))

# Predicted_Job_Loss_2030

df_2030 = df.groupby("Industry").mean(numeric_only=True)
df_2030["Year"] = 2030
pred_2030 = model.predict(df_2030[X.columns])

df_2030["Predicted_Job_Loss_2030"] = pred_2030
df_2030[["Predicted_Job_Loss_2030"]]